name: Package Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build script
      run: npm run build

    - name: Create ZIP file
      run: zip -r chrome-extension.zip manifest.json background.js content.js icons/

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome-extension
        path: chrome-extension.zip
